# Generated by Django 2.0 on 2020-12-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallarymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('catagory', models.CharField(choices=[('Laptop', 'Laptop'), ('mobile', 'mobile'), ('accessories', 'accessories'), ('headphone', 'headphone'), ('light', 'light')], default='Laptop', max_length=50)),
            ],
        ),
    ]
